services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: protexai
      MONGO_INITDB_ROOT_PASSWORD: protexai123
      MONGO_INITDB_DATABASE: protexai
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb

  consumer:
    build:
      context: ./src
      dockerfile: consumer/Dockerfile
    container_name: mqtt-consumer
    depends_on:
      - mosquitto
      - mongodb
    environment:
      MQTT_BROKER_HOST: mosquitto
      MQTT_BROKER_PORT: 1883
      MQTT_TOPIC: protexai/sensors
      MONGODB_URI: mongodb://protexai:protexai123@mongodb:27017/
      MONGODB_DATABASE: protexai
      MONGODB_COLLECTION: metrics
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_CHANNEL: ${SLACK_CHANNEL:-#notifs}
      SLACK_SEND_DURATION_SECONDS: ${SLACK_SEND_DURATION_SECONDS:-30}
    volumes:
      - consumer-logs:/logs

  producer:
    build:
      context: ./src
      dockerfile: producer/Dockerfile
    container_name: mqtt-producer
    depends_on:
      - mosquitto
    environment:
      MQTT_BROKER_HOST: mosquitto
      MQTT_BROKER_PORT: 1883
      MQTT_TOPIC: protexai/sensors
      RUN_INTERVAL_SECONDS: 5
    volumes:
      - producer-logs:/logs

  ui_consumer:
    build:
      context: ./src/ui_consumer
      dockerfile: Dockerfile
      args:
        REACT_APP_MQTT_BROKER: ws://localhost:9001
        REACT_APP_MQTT_TOPIC: protexai/sensors
    container_name: ui-consumer
    ports:
      - "3000:3000"
    depends_on:
      - mosquitto

volumes:
  mosquitto-data:
  mosquitto-logs:
  consumer-logs:
  producer-logs:
  mongodb-data:
  mongodb-config:
