services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log

  consumer:
    build:
      context: ./src
      dockerfile: consumer/Dockerfile
    container_name: mqtt-consumer
    depends_on:
      - mosquitto
    environment:
      MQTT_BROKER_HOST: mosquitto
      MQTT_BROKER_PORT: 1883
      MQTT_TOPIC: protexai/sensors
    volumes:
      - consumer-logs:/logs

  producer:
    build:
      context: ./src
      dockerfile: producer/Dockerfile
    container_name: mqtt-producer
    depends_on:
      - mosquitto
    environment:
      MQTT_BROKER_HOST: mosquitto
      MQTT_BROKER_PORT: 1883
      MQTT_TOPIC: protexai/sensors
      RUN_INTERVAL_SECONDS: 5
    volumes:
      - producer-logs:/logs

volumes:
  mosquitto-data:
  mosquitto-logs:
  consumer-logs:
  producer-logs:
